name: CI Build

on:
  push:
    tags:
      - '*'
    branches:
      - main

jobs:
  Prod-Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PROD
        uses: actions/checkout@v4

      - name: Install Node.js latest
        uses: actions/setup-node@v4
        with:
          node-version: latest
          check-latest: true

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npx eslint --no-error-on-unmatched-pattern.

      - name: Generate build
        env:
          CI: false
        run: npm run build

      # Share artifact
      - name: Share artifact inside workflow
        uses: actions/upload-artifact@v4
        with:
          name: react-github-actions-build
          path: build